"""Testing-time visual reasoning methods and shared experiment infrastructure."""

from .data.cub import (
    CUB200Dataset,
    CubSample,
    CubValidationReport,
    canonical_class_name,
    download_cub,
    prepare_cub,
    validate_class_name_alignment,
    validate_cub,
)
from .methods.fudd.config import OFFICIAL_CLIP_MODEL, OFFICIAL_CLIP_PRECISION, FuDDConfig
from .methods.fudd.evaluation import (
    CandidateRerankResult,
    EvaluationReport,
    FuDDMetrics,
    ParityReport,
    PredictionRecord,
    evaluate_cub,
    rerank_candidates,
    run_clip_cub_experiment,
)
from .methods.fudd.prompts import (
    CUB_CLASS_COUNT,
    CUB_PAIR_COUNT,
    DEFAULT_TEMPLATE,
    FUDD_OFFICIAL_COMMIT,
    ClassPairDescriptions,
    CubPromptRepository,
    DifferentialDescription,
    download_official_prompts,
    load_official_prompts,
    load_pair_overrides,
    verify_official_prompt_assets,
)
from .metrics import (
    TopKAccuracy,
    TransferCounts,
    accuracy_percentage,
    compute_topk_accuracy,
    compute_transfer_counts,
    ordered_predictions,
    topk_hits,
)
from .models import (
    EVA02_CLIP_L14_336,
    OPEN_CLIP_TORCH_VERSION,
    TIMM_VERSION,
    CLIPBackend,
    ImageFeatureSet,
    OpenCLIPBackend,
    OpenCLIPCheckpoint,
    TextFeatureTable,
    VisionLanguageBackend,
)

__all__ = [
    "CLIPBackend",
    "CUB200Dataset",
    "CUB_CLASS_COUNT",
    "CUB_PAIR_COUNT",
    "CandidateRerankResult",
    "ClassPairDescriptions",
    "CubPromptRepository",
    "CubSample",
    "CubValidationReport",
    "DEFAULT_TEMPLATE",
    "DifferentialDescription",
    "EVA02_CLIP_L14_336",
    "EvaluationReport",
    "FuDDConfig",
    "FUDD_OFFICIAL_COMMIT",
    "FuDDMetrics",
    "ImageFeatureSet",
    "OFFICIAL_CLIP_MODEL",
    "OFFICIAL_CLIP_PRECISION",
    "OPEN_CLIP_TORCH_VERSION",
    "OpenCLIPBackend",
    "OpenCLIPCheckpoint",
    "ParityReport",
    "PredictionRecord",
    "TextFeatureTable",
    "TIMM_VERSION",
    "TopKAccuracy",
    "TransferCounts",
    "VisionLanguageBackend",
    "accuracy_percentage",
    "canonical_class_name",
    "compute_topk_accuracy",
    "compute_transfer_counts",
    "download_cub",
    "download_official_prompts",
    "evaluate_cub",
    "load_official_prompts",
    "load_pair_overrides",
    "ordered_predictions",
    "prepare_cub",
    "rerank_candidates",
    "run_clip_cub_experiment",
    "topk_hits",
    "validate_class_name_alignment",
    "validate_cub",
    "verify_official_prompt_assets",
]
